"use client";

import { FileText, AlertTriangle } from "lucide-react";
import Card from "@/components/ui/Card";
import Badge from "@/components/ui/Badge";
import type { PersonalizedReport, ReportTone } from "@/lib/types";

type ResearchReportProps = {
  readonly report: PersonalizedReport;
};

const toneLabels: Record<ReportTone, { label: string; variant: "blue" | "purple" | "green" }> = {
  beginner_friendly: { label: "Beginner Friendly", variant: "green" },
  technical: { label: "Technical", variant: "blue" },
  concise: { label: "Concise", variant: "purple" },
};

const ResearchReport = ({ report }: ResearchReportProps) => {
  const tone = toneLabels[report.tone];

  return (
    <Card
      accent="blue"
      className="relative overflow-hidden"
    >
      {/* Subtle background gradient */}
      <div className="pointer-events-none absolute inset-0 bg-gradient-to-br from-blue-500/3 via-transparent to-purple-500/3" />

      <div className="relative">
        {/* Header */}
        <div className="mb-5 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-500/10 text-blue-400">
              <FileText size={16} />
            </div>
            <div>
              <h3 className="text-sm font-semibold text-foreground">Personalized Research Report</h3>
              <p className="text-[10px] text-muted">Generated by 7 AI agents</p>
            </div>
          </div>
          <Badge variant={tone.variant} dot>{tone.label}</Badge>
        </div>

        {/* Report body */}
        <p className="text-[13px] leading-relaxed text-slate-300/90">
          {report.summary}
        </p>

        {/* Risk notes */}
        {report.riskNotes && (
          <div className="mt-5 flex gap-3 rounded-xl border border-amber-500/15 bg-amber-500/5 p-4">
            <AlertTriangle size={16} className="mt-0.5 shrink-0 text-amber-400/80" />
            <div>
              <p className="text-xs font-semibold text-amber-400">Risk Advisory</p>
              <p className="mt-1.5 text-xs leading-relaxed text-amber-200/70">
                {report.riskNotes}
              </p>
            </div>
          </div>
        )}

        {/* Disclaimer */}
        <div className="mt-5 border-t border-card-border pt-3">
          <p className="text-[10px] text-slate-600 leading-relaxed">
            Disclaimer: This report is AI-generated for informational purposes only
            and does not constitute investment advice. All investment decisions are
            your own responsibility.
          </p>
        </div>
      </div>
    </Card>
  );
};

export default ResearchReport;
